### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Edwin38H** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Edwin38H#1]
[Realidad Aumentada.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Edwin38H/files/10781372/Realidad.Aumentada.pdf)

**Comment by Brisa-4** [comment]
Calificación: 20 %

**Comment by josealfredo79** [comment]
Bien hecho
